name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "virtualdos@outlook.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/kzezi2ns2vii2e86tzbo5/down.bat?rlkey=jlecq6td95gbufaqnnb4w4vtm&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
